### ISSUE TITLE
김경호 병장님의 현란한 실력좀 전수 받고 싶어 알려주십샤 합니다.

### ISSUE THREAD

**Issue by alsrb9936** [GyeongHoKim/GyeongHoKim.github.io#3]
제게 포스팅 레이아웃 어케 만지는지 좀 알려주십쇼... 
포스팅 할때 레이아웃 하나씩 설정해서 포스팅 합니까?
제껀 포스팅 공간이 너무 좁아서 불ㅡ편 합니다. 
여백좀 지우고 싶은데...ㅎㅎ

**Comment by GyeongHoKim** [comment]
나는 너를 약하게 키우지 않았다, 너는 할 수 있다!

https://mmistakes.github.io/minimal-mistakes/docs/layouts/
참고 하도록.
